title: Sahil Gogna
logo: /sahil-headshot.png
description: Mentoring data aspirants to become Top 1% (and beyond) | Senior Data Engineer at RBC Canada
#show_downloads: true
theme: jekyll-theme-minimal
